server:
  port: 8081

spring:
  application:
    name: service-mfw
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/shixuner?useUnicode=true&characterEncoding=utf-8
    username: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
mybatis:
  config-locations: classpath:mybatis/confg.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.jk.model

